### ISSUE TITLE
I laugh, sorry

### ISSUE THREAD

**Issue by av-vonsbak** [Sol-Sanctum/Zenon-Vanity-Address-Generator#1]
[Reference here](https://github.com/Sol-Sanctum/Zenon-Vanity-Address-Generator/blob/main/vanity.dart#L24)

**Comment by av-vonsbak** [comment]
If you're interested in a new `KeyStore`, you can use [KeyStore.newRandom()](https://github.com/zenon-network/znn_sdk_dart/blob/master/lib/src/wallet/keystore.dart#L28)

**Comment by sol-znn** [comment]
> If you're interested in a new `KeyStore`, you can use [KeyStore.newRandom()](https://github.com/zenon-network/znn_sdk_dart/blob/master/lib/src/wallet/keystore.dart#L28)

Hahaha I must have missed that the first time I read through the SDK functions! Thanks for the suggestion!

**Comment by av-vonsbak** [comment]
Awesome!
